### PR TITLE
Fix USERDATA_FSTYPE

### PR DESCRIPTION
**Pull request by wangyou**
Repair partition to ext3.And edison virtual partitions on userdata, so "$LOOP_DEV" = "-userdata"

### CODE REVIEW

**Comment by Aceofzeroz** [comment]
Wang, I'd like to suggest aside from trying to get Safestrap to work, you could also try disabling SELinux in the edison device source if you know how. I've finally given up on Safestrap after almost losing my device, so I can't do anything more for getting Android 5.0.

**Comment by wangyou** [comment]
I have an idea，Do not use common-omap4, use common-hd, because we do not have internal memory, happened, common-hd met, we may be slightly modified, it is worth a try?I'm synchronization source, but China visit github very slow ~You've worked hard。I will try.try.try～～～

**Comment by Aceofzeroz** [comment]
I tried something like that and it still didn't seem to be any different from using common-omap4. I just don't know what part is holding us back so badly, but thanks for your appreciation. I know open internet speed isn't the best there, but I certainly hope you have better luck finding a way to booting 5.0 LP. Take care Wang! :-)

**Comment by wangyou** [comment]
OK，i will try

**Comment by Aceofzeroz** [comment]
Happy New Lunar Year Wang! :D I wish you and all of China a prosperous and successful Year of the Ram ! ҉٩(_´︶`_)۶҉

**Comment by wangyou** [comment]
Thank you so much ！Yesterday I was very busy! Whole family the reunion dinner together, very lively. I hope you have come China to experience! Hehe……

**Comment by Aceofzeroz** [comment]
I'm glad to hear that it's going so well for you and your family, I really hope to travel there one day to be a part of it! ^_^

**Pull request closed without merging**
